<?php
namespace App\Constants;

class GlosaTransaccion
{
    //Transacciones a la billetera de causa
    const CREDITO_DESDE_BILLETERA = 'SE ACREDITÓ A LA CAUSA DESDE LA BILLETERA GENERAL';
    const CREDITO_DESDE_CAUSA = 'SE ACREDITÓ A LA CAUSA DESDE OTRA CAUSA';
    const DEBITO_POR_TRASPASO = 'SE DEBITÓ POR TRASPASO A OTRA CAUSA';
    const DEBITO_POR_DEVOLUCION_A_BILLETERA_GRAL = 'SE DEBITÓ POR DEVOLUCIÓN A BILLETERA GENERAL';
    const DEBITO_POR_EGRESO_ORDEN = 'SE DEBITÓ POR GASTO DE ORDEN #';
    //Transacciones de Billetera general
    const DEBITO_DESDE_BILLETERA_POR_TRANSFERENCIA_A_CAUSA = 'SE DEBITÓ DE LA BILLETERA GENERAL POR TRANSFERENCIA A LA CAUSA';
    const CREDITO_DEPOSITO_A_BILLETERA = 'SE ACREDITÓ A LA BILLETERA GENERAL POR CONCEPTO DE DEPOSITO';
    const CREDITO_DEPOSITO_A_BILLETERA_FROM_ADMIN = 'SE ACREDITÓ A LA BILLETERA GENERAL POR CONCEPTO DE DEPOSITO DESDE EL ADMINISTRADOR';
    const DEBITO_POR_COMPRA_DEL_PAQUETE = 'SE DEBITÓ POR COMPRA DEL PAQUETE';
    const CREDITO_DEVOLUCION_DE_CAUSA = 'SE ACREDITÓ A LA BILLETERA GENERAL POR DEVOLUCIÓN DE SALDO DE LA CAUSA';
    const DEBITO_EGRESO_ORDEN_BILL_GRAL = 'SE DEBITÓ POR GASTO DE ORDEN #';
    const DEBITO_POR_DEVOLUCION_SALDO_BILLETERA_GRAL = 'SE DEBITÓ DE LA BILLETERA GENERAL POR DEVOLUCIÓN DE SALDO';
    //Transacciones caja de admin
    const CREDITO_POR_DEPOSITO_ABOGADO = 'SE ACREDITÓ A LA CAJA DEL ADMINISTRADOR POR DEPOSITO DEL ABOGADO A SU BILLETERA';
    const DEBITO_POR_DEPOSITO_CONTADOR = 'SE DEBITÓ POR DEPOSITO A LA CAJA DEL CONTADOR';
    const CREDITO_POR_DEVOLUCION_CONTADOR = 'SE ACREDITÓ A LA CAJA DEL ADMINISTRADOR POR DEVOLUCIÓN DEL CONTADOR';
    const DEBITO_POR_PAGO_PROCURADURIA = 'SE DEBITÓ DE LA CAJA DEL ADMINISTRADOR POR PAGO DE PROCURADURIA DE LAS ORDENES: ';
    const CREDITO_POR_PAGO_PROCURADURIA = 'SE ACREDITÓ A LA CAJA DEL ADMINISTRADOR POR PAGO EXTRAORDINARIO DE PROCURADURIA DE LAS ORDENES: ';
    const DEBITO_POR_RETIRO = 'SE DEBITÓ DE LA CAJA DEL ADMINISTRADOR POR EL CONCEPTO DE RETIRO';
    const DEBITO_POR_DEVOLUCION_SALDO = 'SE DEBITÓ DE LA CAJA DEL ADMINISTRADOR POR DEVOLUCION DE SALDO AL ABOGADO';
    //Transacciones caja del contador
    const CREDITO_POR_DEPOSITO_ADMIN = 'SE ACREDITÓ A LA CAJA DEL CONTADOR POR DEPOSITO DEL ADMINISTRADOR';
    const EGRESO_POR_DEVOLUCION_ADMIN = 'SE DEBITÓ DE LA CAJA DEL CONTADOR POR DEVOLUCIÓN AL ADMINISTRADOR';
    const DEBITO_POR_ENTREGA_PRESUPUESTO = 'SE DEBITÓ DE LA CAJA DEL CONTADOR POR ENTREGA DE PRESUPUESTO DE LAS ORDENES :';
    const DEBITO_POR_DEVOLUCION_PRESUPUESTO = 'SE DEBITÓ DE LA CAJA DEL CONTADOR POR DEVOLUCION DE PRESUPUESTO DE LAS ORDENES :';
    const CREDITO_POR_DEVOLUCION_PRESUPUESTO = 'SE ACREDITÓ A LA CAJA DEL CONTADOR POR DEVOLUCION DE PRESUPUESTO DE LAS ORDENES :';
    //Pago procurador
    const PAGO_A_PROCURADOR = 'SE CANCELO AL PROCURADOR POR CONCEPTO DE PAGO POR LAS ORDENES: ';
    const PAGO_A_PROCURADOR_EXTRAORDINARIO = 'PAGO EXTRAORDINARIO DE PROCURADOR POR CONCEPTO DE PAGO POR LAS ORDENES: ';
}
