<?php
namespace App\Constants;

class Transaccion
{
    //Transacciones de admin
    const INGRESO_POR_DEPOSITO_ABOGADO = 'INGRESO_POR_DEPOSITO_ABOGADO';
    const EGRESO_POR_DEPOSITO_CONTADOR = 'EGRESO_POR_DEPOSITO_CONTADOR';
    const INGRESO_POR_DEVOLUCION_CONTADOR = 'INGRESO_POR_DEVOLUCION_CONTADOR';
    const EGRESO_POR_PAGO_PROCURADURIA = 'EGRESO_POR_PAGO_PROCURADURIA';
    const INGRESO_POR_PAGO_PROCURADURIA = 'INGRESO_POR_PAGO_PROCURADURIA';
    const EGRESO_POR_RETIRO = 'EGRESO_POR_RETIRO';
    const EGRESO_POR_DEVOLUCION_ABOGADO = 'EGRESO_POR_DEVOLUCION_ABOGADO';
    //Transacciones de contador
    const INGRESO_POR_DEPOSITO_ADMIN = 'INGRESO_POR_DEPOSITO_ADMIN';
    const EGRESO_POR_DEVOLUCION_ADMIN = 'EGRESO_POR_DEVOLUCION_ADMIN';
    const EGRESO_POR_ENTREGA_PRESUPUESTO = 'EGRESO_POR_ENTREGA_PRESUPUESTO';
    const EGRESO_POR_DEVOLUCION_PRESUPUESTO = 'EGRESO_POR_DEVOLUCION_PRESUPUESTO';
    const INGRESO_POR_DEVOLUCION_PRESUPUESTO = 'INGRESO_POR_DEVOLUCION_PRESUPUESTO';
   
}